<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'administrator',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('password'),
                'role' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
                'role' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('categories')->insert([
            [
                'name' => 'iPhone',
                'slug' => 'iphone',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'name' => 'iPad',
                'slug' => 'ipad',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'name' => 'Macbook',
                'slug' => 'macbook',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'name' => 'Apple Watch',
                'slug' => 'apple-watch',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]
        ]);

        DB::table('products')->insert([
            [
                'category' => 1,
                'name' => 'iPhone X 64GB Đen',
                'slug' => 'iphone-x-64gb-den',
                'img' => 'iphone-x-64gb-den.jpg',
                'price' => 6000000,
                'sale' => 5200000,
                'qty' => 15,
                'featured' => false,
                'sold' => 3,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone X 128GB Đen',
                'slug' => 'iphone-x-128gb-den',
                'img' => 'iphone-x-128gb-den.jpg',
                'price' => 6500000,
                'sale' => 6000000,
                'qty' => 13,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone Xs 128GB Trắng',
                'slug' => 'iphone-xs-128gb-trang',
                'img' => 'iphone-xs-128gb-trang.jpg',
                'price' => 7500000,
                'sale' => 6500000,
                'qty' => 7,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone Xs 256GB Vàng',
                'slug' => 'iphone-xs-256gb-vang',
                'img' => 'iphone-xs-256gb-vang.jpg',
                'price' => 7500000,
                'sale' => 6600000,
                'qty' => 9,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone Xs Max 128GB Vàng',
                'slug' => 'iphone-xs-max-128gb-vang',
                'img' => 'iphone-xs-max-128gb-vang.jpg',
                'price' => 8500000,
                'sale' => 7500000,
                'qty' => 11,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone Xs Max 512GB Trắng',
                'slug' => 'iphone-xs-max-512gb-trang',
                'img' => 'iphone-xs-max-512gb-trang.jpg',
                'price' => 9000000,
                'sale' => 8000000,
                'qty' => 4,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 64GB Trắng',
                'slug' => 'iphone-11-64gb-trang',
                'img' => 'iphone-11-64gb-trang.jpg',
                'price' => 9500000,
                'sale' => 8500000,
                'qty' => 12,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 64GB Đen',
                'slug' => 'iphone-11-64gb-den',
                'img' => 'iphone-11-64gb-den.jpg',
                'price' => 9500000,
                'sale' => 8500000,
                'qty' => 12,
                'featured' => false,
                'sold' => 2,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 Pro 64GB Đen',
                'slug' => 'iphone-11-pro-64gb-den',
                'img' => 'iphone-11-pro-64gb-den.jpg',
                'price' => 10500000,
                'sale' => 9000000,
                'qty' => 12,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 128GB Tím',
                'slug' => 'iphone-11-128gb-tim',
                'img' => 'iphone-11-128gb-tim.jpg',
                'price' => 11000000,
                'sale' => 10000000,
                'qty' => 19,
                'featured' => false,
                'sold' => 2,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 128GB Trắng',
                'slug' => 'iphone-11-128gb-trang',
                'img' => 'iphone-11-128gb-trang.jpg',
                'price' => 11000000,
                'sale' => 10000000,
                'qty' => 11,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 11 128GB Xanh Lá',
                'slug' => 'iphone-11-128gb-xanh-la',
                'img' => 'iphone-11-128gb-xanh-la.jpg',
                'price' => 11000000,
                'sale' => 10000000,
                'qty' => 27,
                'featured' => false,
                'sold' => 8,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 12 128GB Tím',
                'slug' => 'iphone-12-128gb-tim',
                'img' => 'iphone-12-128gb-tim.jpg',
                'price' => 12500000,
                'sale' => 11000000,
                'qty' => 32,
                'featured' => false,
                'sold' => 9,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 12 128GB Trắng',
                'slug' => 'iphone-12-128gb-trang',
                'img' => 'iphone-12-128gb-trang.jpg',
                'price' => 12500000,
                'sale' => 11000000,
                'qty' => 42,
                'featured' => false,
                'sold' => 14,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 12 128GB Xanh Lá',
                'slug' => 'iphone-12-128gb-xanh-la',
                'img' => 'iphone-12-128gb-xanh-la.jpg',
                'price' => 12500000,
                'sale' => 11000000,
                'qty' => 41,
                'featured' => false,
                'sold' => 21,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 13 128GB Blue',
                'slug' => 'iphone-13-128gb-blue',
                'img' => 'iphone-13-128gb-blue.jpg',
                'price' => 13900000,
                'sale' => 12700000,
                'qty' => 34,
                'featured' => false,
                'sold' => 8,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 13 256GB Midnight',
                'slug' => 'iphone-13-256gb-midnight',
                'img' => 'iphone-13-256gb-midnight.jpg',
                'price' => 13900000,
                'sale' => 13200000,
                'qty' => 27,
                'featured' => false,
                'sold' => 3,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 13 Pro Max 128GB Bạc',
                'slug' => 'iphone-13-pro-max-128gb-bac',
                'img' => 'iphone-13-pro-max-128gb-bac.jpg',
                'price' => 20500000,
                'sale' => 16700000,
                'qty' => 35,
                'featured' => false,
                'sold' => 9,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 13 Pro Max 128GB Vàng',
                'slug' => 'iphone-13-pro-max-128gb-vang',
                'img' => 'iphone-13-pro-max-128gb-vang.jpg',
                'price' => 20500000,
                'sale' => 16700000,
                'qty' => 35,
                'featured' => false,
                'sold' => 8,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 13 Pro Max 256GB Xanh Lá',
                'slug' => 'iphone-13-pro-max-256gb-xanh-la',
                'img' => 'iphone-13-pro-max-256gb-xanh-la.jpg',
                'price' => 20500000,
                'sale' => 17000000,
                'qty' => 35,
                'featured' => false,
                'sold' => 24,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 14 256GB Đen',
                'slug' => 'iphone-14-256gb-den',
                'img' => 'iphone-14-256gb-den.jpg',
                'price' => 19800000,
                'sale' => 19000000,
                'qty' => 33,
                'featured' => false,
                'sold' => 3,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 14 256GB Đỏ',
                'slug' => 'iphone-14-256gb-do',
                'img' => 'iphone-14-256gb-do.jpg',
                'price' => 19800000,
                'sale' => 19000000,
                'qty' => 42,
                'featured' => false,
                'sold' => 5,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 14 Pro Max 256GB Đen',
                'slug' => 'iphone-14-pro-max-256gb-den',
                'img' => 'iphone-14-pro-max-256gb-den.jpg',
                'price' => 23800000,
                'sale' => 23000000,
                'qty' => 62,
                'featured' => true,
                'sold' => 11,
                'status' => 1,
                'description' => '<p>A new, larger 6.7-inch size joins the popular 6.1-inch design, featuring a new dual-camera system, Crash Detection, a smartphone industry-first safety service with Emergency SOS via satellite, and the best battery life on iPhone.</p>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 14 Pro Max 256GB Vàng',
                'slug' => 'iphone-14-pro-max-256gb-vang',
                'img' => 'iphone-14-pro-max-256gb-vang.jpg',
                'price' => 23800000,
                'sale' => 23500000,
                'qty' => 56,
                'featured' => true,
                'sold' => 10,
                'status' => 1,
                'description' => '<p>A new, larger 6.7-inch size joins the popular 6.1-inch design, featuring a new dual-camera system, Crash Detection, a smartphone industry-first safety service with Emergency SOS via satellite, and the best battery life on iPhone.</p>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 1,
                'name' => 'iPhone 14 Pro Max 256GB Tím',
                'slug' => 'iphone-14-pro-max-256gb-tim',
                'img' => 'iphone-14-pro-max-256gb-tim.jpg',
                'price' => 23800000,
                'sale' => 23500000,
                'qty' => 67,
                'featured' => true,
                'sold' => 33,
                'status' => 1,
                'description' => '<p>A new, larger 6.7-inch size joins the popular 6.1-inch design, featuring a new dual-camera system, Crash Detection, a smartphone industry-first safety service with Emergency SOS via satellite, and the best battery life on iPhone.</p>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Air M1 2020 8GB/256GB Xám',
                'slug' => 'macbook-air-m1-2020-8gb-256gb-xam',
                'img' => 'macbook-air-m1-2020-8gb-256gb-xam.jpg',
                'price' => 22990000,
                'sale' => 18490000,
                'qty' => 35,
                'featured' => false,
                'sold' => 14,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Air M2 2022 8GB/256GB Bạc',
                'slug' => 'macbook-air-m2-2022-8gb-256gb-bac',
                'img' => 'macbook-air-m2-2022-8gb-256gb-bac.jpg',
                'price' => 32990000,
                'sale' => 27690000,
                'qty' => 15,
                'featured' => false,
                'sold' => 7,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Pro M2 2022 8GB/256GB Bạc',
                'slug' => 'macbook-pro-m2-2022-8gb-256gb-bac',
                'img' => 'macbook-pro-m2-2022-8gb-256gb-bac.jpg',
                'price' => 35990000,
                'sale' => 28890000,
                'qty' => 11,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Pro 14 inch M2 Pro 2023 16GB/512GB Xám',
                'slug' => 'macbook-pro-14-inch-m2-pro-2023-16gb-512gb-xam',
                'img' => 'macbook-pro-14-inch-m2-pro-2023-16gb-512gb-xam.jpg',
                'price' => 52990000,
                'sale' => 51990000,
                'qty' => 6,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Pro 16 inch M2 Pro 2023 16GB/512GB Bạc',
                'slug' => 'macbook-pro-16-inch-m2-pro-2023-16gb-512gb-bac',
                'img' => 'macbook-pro-16-inch-m2-pro-2023-16gb-512gb-bac.jpg',
                'price' => 65990000,
                'sale' => 64990000,
                'qty' => 3,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Air M2 2022 16GB/512GB Vàng',
                'slug' => 'macbook-air-m2-2022-16gb-512gb-vang',
                'img' => 'macbook-air-m2-2022-16gb-512gb-vang.jpg',
                'price' => 46990000,
                'sale' => 39690000,
                'qty' => 15,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Pro 13 inch M2 2022 16GB/512GB Bạc',
                'slug' => 'macbook-pro-13-inch-m2-2022-16gb-512gb-bac',
                'img' => 'macbook-pro-13-inch-m2-2022-16gb-512gb-bac.jpg',
                'price' => 45990000,
                'sale' => 37390000,
                'qty' => 8,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 3,
                'name' => 'MacBook Pro M1 2020 16GB/512GB Xám',
                'slug' => 'macbook-pro-m1-2020-16gb-512gb-xam',
                'img' => 'macbook-pro-m1-2020-16gb-512gb-xam.jpg',
                'price' => 42690000,
                'sale' => 33990000,
                'qty' => 12,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad 9 WiFi 64GB Bạc',
                'slug' => 'ipad-9-wifi-64gb-bac',
                'img' => 'ipad-9-wifi-64gb-bac.jpg',
                'price' => 9990000,
                'sale' => 7190000,
                'qty' => 24,
                'featured' => false,
                'sold' => 12,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad 10 WiFi 64GB Bạc',
                'slug' => 'ipad-10-wifi-64gb-bac',
                'img' => 'ipad-10-wifi-64gb-bac.jpg',
                'price' => 12990000,
                'sale' => 11190000,
                'qty' => 24,
                'featured' => false,
                'sold' => 12,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Pro M1 11 inch WiFi 2TB 2021 Bạc',
                'slug' => 'ipad-pro-m1-11-inch-wifi-2tb-2021-bac',
                'img' => 'ipad-pro-m1-11-inch-wifi-2tb-2021-bac.jpg',
                'price' => 49990000,
                'sale' => 44990000,
                'qty' => 6,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Air 5 M1 Wifi Cellular 256GB Hồng',
                'slug' => 'ipad-air-5-m1-wifi-cellular-256gb-hong',
                'img' => 'ipad-air-5-m1-wifi-cellular-256gb-hong.jpg',
                'price' => 24990000,
                'sale' => 21990000,
                'qty' => 8,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad mini 6 WiFi 64GB Hồng',
                'slug' => 'ipad-mini-6-wifi-64gb-hong',
                'img' => 'ipad-mini-6-wifi-64gb-hong.jpg',
                'price' => 14990000,
                'sale' => 12040000,
                'qty' => 8,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Pro M1 12.9 inch WiFi Cellular 128GB Bạc',
                'slug' => 'ipad-pro-m1-12-9-inch-wifi-cellular-128gb-bac',
                'img' => 'ipad-pro-m1-12-9-inch-wifi-cellular-128gb-bac.jpg',
                'price' => 34990000,
                'sale' => 29290000,
                'qty' => 5,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Pro M1 11 inch WiFi Cellular 2TB 2021 Xám',
                'slug' => 'ipad-pro-m1-11-inch-wifi-cellular-2tb-2021-xam',
                'img' => 'ipad-pro-m1-11-inch-wifi-cellular-2tb-2021-xam.jpg',
                'price' => 55990000,
                'sale' => 50990000,
                'qty' => 8,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Pro M1 12.9 inch WiFi 128GB 2021 Bạc',
                'slug' => 'ipad-pro-m1-12-9-inch-wifi-128gb-2021-bac',
                'img' => 'ipad-pro-m1-12-9-inch-wifi-128gb-2021-bac.jpg',
                'price' => 30990000,
                'sale' => 25490000,
                'qty' => 6,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Pro M2 11 inch WiFi 128GB Xám',
                'slug' => 'ipad-pro-m2-11-inch-wifi-128gb-xam',
                'img' => 'ipad-pro-m2-11-inch-wifi-128gb-xam.jpg',
                'price' => 23990000,
                'sale' => 20990000,
                'qty' => 6,
                'featured' => false,
                'sold' => 1,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad mini 6 WiFi Cellular 64GB Starlight',
                'slug' => 'ipad-mini-6-wifi-cellular-64gb-starlight',
                'img' => 'ipad-mini-6-wifi-cellular-64gb-starlight.jpg',
                'price' => 19990000,
                'sale' => 15700000,
                'qty' => 17,
                'featured' => false,
                'sold' => 5,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad Air 5 M1 Wifi 64GB Xám',
                'slug' => 'ipad-air-5-m1-wifi-64gb-xam',
                'img' => 'ipad-air-5-m1-wifi-64gb-xam.jpg',
                'price' => 16990000,
                'sale' => 14190000,
                'qty' => 12,
                'featured' => false,
                'sold' => 3,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad 10 WiFi Cellular 64GB Blue',
                'slug' => 'ipad-10-wifi-cellular-64gb-blue',
                'img' => 'ipad-10-wifi-cellular-64gb-blue.jpg',
                'price' => 16990000,
                'sale' => 14290000,
                'qty' => 16,
                'featured' => false,
                'sold' => 5,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 2,
                'name' => 'iPad 9 WiFi Cellular 64GB Trắng',
                'slug' => 'ipad-9-wifi-cellular-64gb-trang',
                'img' => 'ipad-9-wifi-cellular-64gb-trang.jpg',
                'price' => 12990000,
                'sale' => 9990000,
                'qty' => 35,
                'featured' => false,
                'sold' => 14,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch SE 2022 GPS 40mm',
                'slug' => 'apple-watch-se-2022-gps-40mm',
                'img' => 'apple-watch-se-2022-gps-40mm.jpg',
                'price' => 7490000,
                'sale' => 5990000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch SE 2022 GPS 44mm',
                'slug' => 'apple-watch-se-2022-gps-44mm',
                'img' => 'apple-watch-se-2022-gps-44mm.jpg',
                'price' => 8490000,
                'sale' => 6890000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch S8 GPS 41mm',
                'slug' => 'apple-watch-s8-gps-41mm',
                'img' => 'apple-watch-s8-gps-41mm.jpg',
                'price' => 11990000,
                'sale' => 8990000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch S8 GPS 45mm',
                'slug' => 'apple-watch-s8-gps-45mm',
                'img' => 'apple-watch-s8-gps-45mm.jpg',
                'price' => 12990000,
                'sale' => 10190000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch S8 LTE 45mm',
                'slug' => 'apple-watch-s8-lte-45mm',
                'img' => 'apple-watch-s8-lte-45mm.jpg',
                'price' => 15990000,
                'sale' => 12490000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch S8 LTE 41mm',
                'slug' => 'apple-watch-s8-lte-41mm',
                'img' => 'apple-watch-s8-lte-41mm.jpg',
                'price' => 14990000,
                'sale' => 11990000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch Ultra LTE 49mm',
                'slug' => 'apple-watch-ultra-lte-49mm',
                'img' => 'apple-watch-ultra-lte-49mm.jpg',
                'price' => 23990000,
                'sale' => 18990000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch SE 2022 LTE 44mm',
                'slug' => 'apple-watch-se-2022-lte-44mm',
                'img' => 'apple-watch-se-2022-lte-44mm.jpg',
                'price' => 9990000,
                'sale' => 7990000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'category' => 4,
                'name' => 'Apple Watch SE 2022 LTE 40mm',
                'slug' => 'apple-watch-se-2022-lte-40mm',
                'img' => 'apple-watch-se-2022-lte-40mm.jpg',
                'price' => 8990000,
                'sale' => 7290000,
                'qty' => 10,
                'featured' => false,
                'sold' => 0,
                'status' => 1,
                'description' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
